### ISSUE TITLE
Add a require for `_withdrawAmount` on `withdraw()`

### ISSUE THREAD

**Issue by joswha** [m-brantheim/scream-leverage#7]
_withdrawAmount has to be checked in `withdraw()`.
```
require(_withdrawAmount !=0, "_withdrawAmount > 0");
```
https://github.com/m-brantheim/scream-leverage/blob/16cf7a3b25aa6d900d09e584dcb1852c71aca424/contracts/ReaperAutoCompoundScreamLeverage.sol#L90-L114

Not doing so can lead to `withdrawFee = 0` in `_withdrawUnderlyingToVault()`.

https://github.com/m-brantheim/scream-leverage/blob/16cf7a3b25aa6d900d09e584dcb1852c71aca424/contracts/ReaperAutoCompoundScreamLeverage.sol#L473-L478

**Comment by m-brantheim** [comment]
The function is vault only, and the vault already has a check:
require(_shares > 0, "please provide amount");
