### ISSUE TITLE
Check `return` value of `incrementDeposits()` and `incrementWithdrawals()`

### ISSUE THREAD

**Issue by joswha** [m-brantheim/scream-leverage#8]
Although not a security issue per se, the functions that are called return a `bool` which isn't checked. The `bool` doesn't seem to have any use case whatsoever, since the operations executed prior to it would revert(in case of an overflow) the transaction anyways(eg. the `cumulativeWithdrawals[tx.origin] = newTotal;` in `incrementWithdrawals()`).

Would recommend removing the `return` statement altogether.

`incrementWithdrawals()` called in: 
https://github.com/m-brantheim/scream-leverage/blob/main/contracts/ReaperVaultv1_3.sol#L247
`incrementDeposits()` called in: 
https://github.com/m-brantheim/scream-leverage/blob/main/contracts/ReaperVaultv1_3.sol#L206

**Comment by m-brantheim** [comment]
The return could be for gas savings as returning something can be cheaper than returning nothing.
In any case it is in the vault code which was not worked on in this repository so it should be addressed somewhere else.
